### ISSUE TITLE
`ajv` initialized with `strict:false` fails to detect missing required objects

### ISSUE THREAD

**Issue by stiebitzhofer** [s1seven/EN10168-schemas#13]
In the new script `validate_spec.js` in line 13 `ajv` is initialized with

```
    const ajv = new Ajv({ strict: false, allErrors: true });
```

`strict` set to false fails to detect missing required elements. If set to `true` it works properly.

**Comment by stiebitzhofer** [comment]
If set to `true` ajv complains about `meta:license`, which is something not within the JSON Schema standard. Should we simply drop it?

**Comment by getlarge** [comment]
Could you tell which elements were missing ?

As a reminder, this AJV instance is only validating the schema.json in the repository against the JSON schema (http://json-schema.org/draft-07/schema) and not some certificates.
I'm saying this because in #14 you seemed to make the confusion.

Also the PR is a more appropriate place to add your change requests.

**Comment by stiebitzhofer** [comment]
Ok. On the missing element, I did some update of the Tata JSONs as they are a bit outdated. Finding out that `OtherTests` is mandatory. Now removing it from the sample without changing the schema didnot result in an error.
